import pandas as pd

from simulator.retirement_score import retirement_score

# Plain-language asset class per ticker (see main.py's TICKERS) - tickers alone don't
# mean much to someone who isn't already familiar with them, so recommendations are
# described by what they actually are, not just the fund symbol.
TICKER_ASSET_CLASS: dict[str, str] = {
    "SPY": "미국 대형주",
    "QQQ": "미국 나스닥 성장주",
    "QLD": "미국 나스닥 성장주(2배 레버리지)",
    "TQQQ": "미국 나스닥 성장주(3배 레버리지)",
    "SSO": "미국 대형주(2배 레버리지)",
    "UPRO": "미국 대형주(3배 레버리지)",
    "VTI": "미국 전체주식",
    "SCHD": "미국 배당성장주",
    "NOBL": "미국 배당귀족주",
    "VEA": "선진국주식(미국 제외)",
    "VWO": "신흥국주식",
    "TLT": "미국 장기국채",
    "IEF": "미국 중기국채",
    "BND": "미국 종합채권",
    "SGOV": "미국 단기국채(현금성)",
    "GLD": "금",
    "DBC": "원자재",
}


def describe_ticker(ticker: str) -> str:
    """`"IEF(미국 중기국채)"` for a known ticker, or just `ticker` if unmapped."""
    asset_class = TICKER_ASSET_CLASS.get(ticker)
    return f"{ticker}({asset_class})" if asset_class else ticker


def recommend_portfolios(
    results: pd.DataFrame,
    tickers: list[str],
    withdrawal_rate: float,
    total_assets: float,
    survival_weight: float = 100.0,
    growth_weight: float = 20.0,
    risk_weight: float = 50.0,
    longevity_weight: float = 10.0,
    top_n: int = 3,
    rate_tolerance: float = 1e-6,
) -> list[dict]:
    """Pick `top_n` portfolios from a precomputed `results` table (see main.py's
    RESULTS_CSV) that best match the user's own values (score weights) and their
    chosen withdrawal rate - no re-simulation needed, since retirement_score's raw
    inputs (survival_probability/cagr/mdd/years_survived) were already stored
    per-combo. `total_assets` is only used to translate the withdrawal *rate* into an
    actual monthly amount for this user.

    Diversity: only the single best-scoring row per distinct *set of active tickers*
    is kept, so the 3 recommendations aren't near-duplicates of the same allocation
    at slightly different weights."""
    matching = results[(results["withdrawal_rate"] - withdrawal_rate).abs() < rate_tolerance]

    scored = matching.assign(
        score=[
            retirement_score(
                row.survival_probability,
                row.cagr,
                row.mdd,
                row.years_survived,
                survival_weight=survival_weight,
                growth_weight=growth_weight,
                risk_weight=risk_weight,
                longevity_weight=longevity_weight,
            )
            for row in matching.itertuples()
        ]
    ).sort_values("score", ascending=False)

    picked_ticker_sets: set[frozenset] = set()
    recommendations = []
    for row in scored.itertuples():
        weights = {t: getattr(row, t) for t in tickers if getattr(row, t) > 0}
        active = frozenset(weights)
        if active in picked_ticker_sets:
            continue
        picked_ticker_sets.add(active)

        depleted = not row.historical_survived
        recommendations.append(
            {
                "weights": weights,
                "retirement_score": row.score,
                "withdrawal_rate": row.withdrawal_rate,
                "survival_probability": row.survival_probability,
                "cagr": row.cagr,
                "mdd": row.mdd,
                "final_value": row.final_value,
                "data_start": row.data_start,
                "data_years": row.data_years,
                "monthly_withdrawal": total_assets * withdrawal_rate / 12,
                "depleted": depleted,
                "depleted_at": _estimate_depletion_date(row) if depleted else None,
            }
        )
        if len(recommendations) == top_n:
            break

    return recommendations


def _estimate_depletion_date(row) -> str:
    """Only the single fixed-start historical backtest (not the perpetual multi-window
    one) tracks *when* a depleted portfolio ran out - years_survived is the fraction of
    that run's span it lasted. Approximate, not exact (real deplation could land on any
    day, not just proportionally through the span), but honest about its only source."""
    start = pd.Timestamp(row.data_start)
    days_survived = row.years_survived * row.data_years * 365.25
    return (start + pd.Timedelta(days=days_survived)).date().isoformat()


# One canned opening line per priority - which line is picked is a simple rule (which
# score weight the user set highest), not text generated by a model. Keys must match
# the priority names _dominant_priority() returns.
_PRIORITY_INTROS: dict[str, str] = {
    "survival": "무엇보다 '돈이 안 떨어지는 것'을 가장 중요하게 보시는 것 같아, 안정적으로 오래 버티는 포트폴리오 3가지를 골라봤어요.",
    "growth": "자산을 더 크게 불리는 걸 가장 중요하게 보시는 것 같아, 성장에 무게를 둔 포트폴리오 3가지를 골라봤어요.",
    "risk": "큰 하락을 피하는 걸 가장 중요하게 보시는 것 같아, 변동성이 적은 포트폴리오 3가지를 골라봤어요.",
}


def _dominant_priority(survival_weight: float, growth_weight: float, risk_weight: float) -> str:
    ranked = [("survival", survival_weight), ("growth", growth_weight), ("risk", risk_weight)]
    return max(ranked, key=lambda pair: pair[1])[0]


def build_intro_message(survival_weight: float, growth_weight: float, risk_weight: float) -> str:
    """Code-based (no LLM) opening line shown once above all recommendations - a
    canned line picked by which score weight the user set highest, not generated
    text. Per-recommendation facts live in build_rank_explanation() instead, one per
    card, since a single intro only ever spoke to the #1 pick."""
    priority = _dominant_priority(survival_weight, growth_weight, risk_weight)
    return _PRIORITY_INTROS[priority]


def build_rank_explanation(rec: dict, rank: int, total_assets: float) -> str:
    """Code-based (no LLM) one-line summary for a single recommendation card: what's
    in it and what actually happened to the money (in this user's own won, not an
    abstract multiplier)."""
    allocation = ", ".join(
        f"{describe_ticker(t)} {w:.0%}" for t, w in sorted(rec["weights"].items(), key=lambda kv: -kv[1])
    )

    if rec["depleted"]:
        return f"{rank}순위 {allocation} 조합은 과거 데이터 기준 {rec['depleted_at']}경 자산이 바닥난 적이 있어요."

    final_amount = total_assets * rec["final_value"]
    return (
        f"{rank}순위 {allocation} 조합은 {rec['data_years']}년간 한 번도 바닥나지 않고 "
        f"{final_amount:,.0f}원까지 불어났어요."
    )
